### ISSUE TITLE
Firefox doesn't recognize I'm proxied

### ISSUE THREAD

**Issue by pdewouters** [humanmade/hm-proxy#15]
If I visit `/am-i-proxied` in Chrome it says I'm proxied, but not Firefox, even after clearing history, in an incognito tab and restarting FF.
I also get these messages in the terminal
```
channel 4: open failed: administratively prohibited: open failed
channel 4: open failed: administratively prohibited: open failed
channel 17: open failed: administratively prohibited: open failed
channel 18: open failed: administratively prohibited: open failed
```

**Comment by rmccue** [comment]
This may be your Firefox settings; in Network Settings in Firefox, do you have "use system proxy settings" selected?
